name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  # Run Pytest using relative path.
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest -v --full-trace .

  # Run Pytest targeting the symlinked path explicitly.
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest -v --full-trace /tmp/test

  # Use relative path for target and rootdir.
  test3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest --rootdir=. -v --full-trace .

  # Use symlinked path for target and rootdir.
  test4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest --rootdir=/tmp/test -v --full-trace /tmp/test

  # Use symlinked path for target and relative path for rootdir.
  test5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest --rootdir=. -v --full-trace /tmp/test

  # Use symlinked path for rootdir and relative path for target.
  test6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest --rootdir=/tmp/test -v --full-trace .

