name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
      - uses: actions/checkout@v4
      - name: Install pytest
        run: pip install pytest
      - name: Set up symlink
        run: ln -s ${{runner.workspace}} /tmp/test
      - name: Run tests
        working-directory: /tmp/test
        run: pytest -v --full-trace .

